import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Button } from "./Button";
import { Input } from "./Input";
import { SelectBox } from "./SelectBox";
import { TextArea } from "./TextArea";
import { CheckBox } from "./CheckBox";
import { ReactTable } from "./ReactTable";
export { Img, Text, Heading, Button, Input, SelectBox, TextArea, CheckBox, ReactTable };
